### ISSUE TITLE
ux: 

### ISSUE THREAD

**Issue by martinlindhe** [martinlindhe/feng#8]
- should error when no_magic is not a boolean. currently ignored.

this should error:

```yaml
no_magic:
  - offset: 0000
    match: 18 18 2a 1a
```
