### ISSUE TITLE
ux: should error if struct field has "??" and children

### ISSUE THREAD

**Issue by martinlindhe** [martinlindhe/feng#9]
- syntax error like this is not caught, should be error:

```yaml
    u8 Flags: ??
      bit b0000_0001: EndOfRecord
      bit b0000_0010: VideoSector
```
